name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # The script below navigates to your folder and pulls code
          script: |
            cd /root/2602_VorteGoWebsite
            git pull origin master